In [1]:
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import nltk
from nltk import corpus,tokenize
from nltk.corpus import stopwords
import re
from nltk.stem import PorterStemmer, WordNetLemmatizer, porter

nltk.download('punkt')
# tokenizing text in various languages
nltk.download('vader_lexicon')
#determining the sentiment or emotional tone of a piece of text

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\achyu\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package vader_lexicon to
[nltk_data]     C:\Users\achyu\AppData\Roaming\nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!


True

In [35]:
from nltk.sentiment.vader import SentimentIntensityAnalyzer
sia = SentimentIntensityAnalyzer()

In [36]:
abc = "i have ever seen this kind of movie"
sia.polarity_scores(abc)
# neutral sentence

{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}

In [37]:
ab = "i have never seen this kind of amazing movie"
sia.polarity_scores(ab)
#positive sentence

{'neg': 0.0, 'neu': 0.666, 'pos': 0.334, 'compound': 0.5434}

In [38]:
ba = "this was the worst film to ever disgrace the screen"
sia.polarity_scores(ba)
#negative sentence

{'neg': 0.477, 'neu': 0.523, 'pos': 0.0, 'compound': -0.8074}

In [39]:
df = pd.read_csv("D:\Learnbay\ML Real Time Project\Sentiment Analysis\AmazonProductReviewsData.tsv", sep='\t')
df.head()

label                                             review
0   pos  Stuning even for the non-gamer: This sound tra...
1   pos  The best soundtrack ever to anything.: I'm rea...
2   pos  Amazing!: This soundtrack is my favorite music...
3   pos  Excellent Soundtrack: I truly like this soundt...
4   pos  Remember, Pull Your Jaw Off The Floor After He...

In [40]:
df1 = df.copy()
df1.head()

label                                             review
0   pos  Stuning even for the non-gamer: This sound tra...
1   pos  The best soundtrack ever to anything.: I'm rea...
2   pos  Amazing!: This soundtrack is my favorite music...
3   pos  Excellent Soundtrack: I truly like this soundt...
4   pos  Remember, Pull Your Jaw Off The Floor After He...

In [41]:
df['label'].value_counts()

neg    5097
pos    4903
Name: label, dtype: int64

In [42]:
df.loc[0]['review']

'Stuning even for the non-gamer: This sound track was beautiful! It paints the senery in your mind so well I would recomend it even to people who hate vid. game music! I have played the game Chrono Cross but out of all of the games I have ever played it has the best music! It backs away from crude keyboarding and takes a fresher step with grate guitars and soulful orchestras. It would impress anyone who cares to listen! ^_^'

In [43]:
sia.polarity_scores(df.loc[0]['review'])

{'neg': 0.088, 'neu': 0.669, 'pos': 0.243, 'compound': 0.9454}

In [44]:
df.shape

(10000, 2)

In [45]:
df.isnull().sum()

label     0
review    0
dtype: int64

In [46]:
# Preprocessing
  # missing values - no
  # encoding- will handle by SentimentIntensityAnalyzer
  # outlier - not required as it is text
  # scaling - not required as it is text
  # balance - data is already balanced

In [47]:
# polarity score for all data

df['scores'] = df['review'].apply(lambda review:sia.polarity_scores(review))
df.head(10)


label                                             review  \
0   pos  Stuning even for the non-gamer: This sound tra...   
1   pos  The best soundtrack ever to anything.: I'm rea...   
2   pos  Amazing!: This soundtrack is my favorite music...   
3   pos  Excellent Soundtrack: I truly like this soundt...   
4   pos  Remember, Pull Your Jaw Off The Floor After He...   
5   pos  an absolute masterpiece: I am quite sure any o...   
6   neg  Buyer beware: This is a self-published book, a...   
7   pos  Glorious story: I loved Whisper of the wicked ...   
8   pos  A FIVE STAR BOOK: I just finished reading Whis...   
9   pos  Whispers of the Wicked Saints: This was a easy...   

                                              scores  
0  {'neg': 0.088, 'neu': 0.669, 'pos': 0.243, 'co...  
1  {'neg': 0.018, 'neu': 0.837, 'pos': 0.145, 'co...  
2  {'neg': 0.04, 'neu': 0.692, 'pos': 0.268, 'com...  
3  {'neg': 0.09, 'neu': 0.615, 'pos': 0.295, 'com...  
4  {'neg': 0.0, 'neu': 0.746, 'pos': 0.254, 'comp...  
5  {'neg': 0.014, 'neu': 0.737, 'pos': 0.249, 'co...  
6  {'neg': 0.124, 'neu': 0.806, 'pos': 0.069, 'co...  
7  {'neg': 0.072, 'neu': 0.583, 'pos': 0.346, 'co...  
8  {'neg': 0.113, 'neu': 0.712, 'pos': 0.174, 'co...  
9  {'neg': 0.033, 'neu': 0.777, 'pos': 0.19, 'com...

In [48]:
len(df['scores'])

10000

In [49]:
df['compound'] = df['scores'].apply(lambda score_dict:score_dict['compound'])
df.head(10)

label                                             review  \
0   pos  Stuning even for the non-gamer: This sound tra...   
1   pos  The best soundtrack ever to anything.: I'm rea...   
2   pos  Amazing!: This soundtrack is my favorite music...   
3   pos  Excellent Soundtrack: I truly like this soundt...   
4   pos  Remember, Pull Your Jaw Off The Floor After He...   
5   pos  an absolute masterpiece: I am quite sure any o...   
6   neg  Buyer beware: This is a self-published book, a...   
7   pos  Glorious story: I loved Whisper of the wicked ...   
8   pos  A FIVE STAR BOOK: I just finished reading Whis...   
9   pos  Whispers of the Wicked Saints: This was a easy...   

                                              scores  compound  
0  {'neg': 0.088, 'neu': 0.669, 'pos': 0.243, 'co...    0.9454  
1  {'neg': 0.018, 'neu': 0.837, 'pos': 0.145, 'co...    0.8957  
2  {'neg': 0.04, 'neu': 0.692, 'pos': 0.268, 'com...    0.9858  
3  {'neg': 0.09, 'neu': 0.615, 'pos': 0.295, 'com...    0.9814  
4  {'neg': 0.0, 'neu': 0.746, 'pos': 0.254, 'comp...    0.9781  
5  {'neg': 0.014, 'neu': 0.737, 'pos': 0.249, 'co...    0.9900  
6  {'neg': 0.124, 'neu': 0.806, 'pos': 0.069, 'co...   -0.8744  
7  {'neg': 0.072, 'neu': 0.583, 'pos': 0.346, 'co...    0.9900  
8  {'neg': 0.113, 'neu': 0.712, 'pos': 0.174, 'co...    0.8353  
9  {'neg': 0.033, 'neu': 0.777, 'pos': 0.19, 'com...    0.8196

In [50]:
# using for loop(same code as above, but different method)

compound_scores = []

# Iterate through each row in the DataFrame
for index, row in df.iterrows():
    # Extract the 'compound' score from the 'scores' dictionary in the current row
    compound = row['scores']['compound']
    # Append the 'compound' score to the list
    compound_scores.append(compound)

# Add the list of 'compound' scores as a new column in the DataFrame
df['compound'] = compound_scores

# Display the first 10 rows of the updated DataFrame
df.head(10)

label                                             review  \
0   pos  Stuning even for the non-gamer: This sound tra...   
1   pos  The best soundtrack ever to anything.: I'm rea...   
2   pos  Amazing!: This soundtrack is my favorite music...   
3   pos  Excellent Soundtrack: I truly like this soundt...   
4   pos  Remember, Pull Your Jaw Off The Floor After He...   
5   pos  an absolute masterpiece: I am quite sure any o...   
6   neg  Buyer beware: This is a self-published book, a...   
7   pos  Glorious story: I loved Whisper of the wicked ...   
8   pos  A FIVE STAR BOOK: I just finished reading Whis...   
9   pos  Whispers of the Wicked Saints: This was a easy...   

                                              scores  compound  
0  {'neg': 0.088, 'neu': 0.669, 'pos': 0.243, 'co...    0.9454  
1  {'neg': 0.018, 'neu': 0.837, 'pos': 0.145, 'co...    0.8957  
2  {'neg': 0.04, 'neu': 0.692, 'pos': 0.268, 'com...    0.9858  
3  {'neg': 0.09, 'neu': 0.615, 'pos': 0.295, 'com...    0.9814  
4  {'neg': 0.0, 'neu': 0.746, 'pos': 0.254, 'comp...    0.9781  
5  {'neg': 0.014, 'neu': 0.737, 'pos': 0.249, 'co...    0.9900  
6  {'neg': 0.124, 'neu': 0.806, 'pos': 0.069, 'co...   -0.8744  
7  {'neg': 0.072, 'neu': 0.583, 'pos': 0.346, 'co...    0.9900  
8  {'neg': 0.113, 'neu': 0.712, 'pos': 0.174, 'co...    0.8353  
9  {'neg': 0.033, 'neu': 0.777, 'pos': 0.19, 'com...    0.8196

In [51]:
df['comp_score'] = df['compound'].apply(lambda c: 'pos' if c>=0 else 'neg')
df.head(10)

label                                             review  \
0   pos  Stuning even for the non-gamer: This sound tra...   
1   pos  The best soundtrack ever to anything.: I'm rea...   
2   pos  Amazing!: This soundtrack is my favorite music...   
3   pos  Excellent Soundtrack: I truly like this soundt...   
4   pos  Remember, Pull Your Jaw Off The Floor After He...   
5   pos  an absolute masterpiece: I am quite sure any o...   
6   neg  Buyer beware: This is a self-published book, a...   
7   pos  Glorious story: I loved Whisper of the wicked ...   
8   pos  A FIVE STAR BOOK: I just finished reading Whis...   
9   pos  Whispers of the Wicked Saints: This was a easy...   

                                              scores  compound comp_score  
0  {'neg': 0.088, 'neu': 0.669, 'pos': 0.243, 'co...    0.9454        pos  
1  {'neg': 0.018, 'neu': 0.837, 'pos': 0.145, 'co...    0.8957        pos  
2  {'neg': 0.04, 'neu': 0.692, 'pos': 0.268, 'com...    0.9858        pos  
3  {'neg': 0.09, 'neu': 0.615, 'pos': 0.295, 'com...    0.9814        pos  
4  {'neg': 0.0, 'neu': 0.746, 'pos': 0.254, 'comp...    0.9781        pos  
5  {'neg': 0.014, 'neu': 0.737, 'pos': 0.249, 'co...    0.9900        pos  
6  {'neg': 0.124, 'neu': 0.806, 'pos': 0.069, 'co...   -0.8744        neg  
7  {'neg': 0.072, 'neu': 0.583, 'pos': 0.346, 'co...    0.9900        pos  
8  {'neg': 0.113, 'neu': 0.712, 'pos': 0.174, 'co...    0.8353        pos  
9  {'neg': 0.033, 'neu': 0.777, 'pos': 0.19, 'com...    0.8196        pos

## Evaluation Matrix

In [52]:
from sklearn.metrics import confusion_matrix, classification_report,accuracy_score

In [53]:
print(confusion_matrix(df['label'],df['comp_score']))
print("*************************"*5)
print(classification_report(df['label'],df['comp_score']))
print("*************************"*5)
print(accuracy_score(df['label'],df['comp_score']))

[[2629 2468]
 [ 435 4468]]
*****************************************************************************************************************************
              precision    recall  f1-score   support

         neg       0.86      0.52      0.64      5097
         pos       0.64      0.91      0.75      4903

    accuracy                           0.71     10000
   macro avg       0.75      0.71      0.70     10000
weighted avg       0.75      0.71      0.70     10000

*****************************************************************************************************************************
0.7097


In [54]:
# Here we got less accuracy as we have not done proper preprocessing
# SentimentIntensityAnalyzer- this can do preprocessing to some extent,
   # but there are lot of things that will not considered, so better to do manually one by one to get optimum results

## Appraoch-2(using ML)

In [56]:
df1.head()

label                                             review
0   pos  Stuning even for the non-gamer: This sound tra...
1   pos  The best soundtrack ever to anything.: I'm rea...
2   pos  Amazing!: This soundtrack is my favorite music...
3   pos  Excellent Soundtrack: I truly like this soundt...
4   pos  Remember, Pull Your Jaw Off The Floor After He...

In [61]:
df['review'].values

array(['Stuning even for the non-gamer: This sound track was beautiful! It paints the senery in your mind so well I would recomend it even to people who hate vid. game music! I have played the game Chrono Cross but out of all of the games I have ever played it has the best music! It backs away from crude keyboarding and takes a fresher step with grate guitars and soulful orchestras. It would impress anyone who cares to listen! ^_^',
       "The best soundtrack ever to anything.: I'm reading a lot of reviews saying that this is the best 'game soundtrack' and I figured that I'd write a review to disagree a bit. This in my opinino is Yasunori Mitsuda's ultimate masterpiece. The music is timeless and I'm been listening to it for years now and its beauty simply refuses to fade.The price tag on this is pretty staggering I must say, but if you are going to buy any cd for this much money, this is the only one that I feel would be worth every penny.",
       'Amazing!: This soundtrack is my fav

## Preprocessing

In [66]:
preprocessed_reviews = []

# Loop through each review and preprocess it
for sentence in tqdm(df['review'].values):
    # Remove non-alphabet characters and extra spaces using regex
    sentence = re.sub(r'[^a-zA-Z\s]', '', sentence)
    
    # Tokenize the sentence, convert to lowercase, and remove stopwords
    words = sentence.split()
    words = [word.lower() for word in words if word.lower() not in stopwords.words('english')]
    
    # Join the words back into a sentence
    preprocessed_sentence = ' '.join(words)
    
    # Append the preprocessed sentence to the list
    preprocessed_reviews.append(preprocessed_sentence.strip())
    #" hello world ", calling strip() on it will result in "hello world"

# Display the first few preprocessed reviews
for review in preprocessed_reviews[:5]:
    print(review)

100%|██████████████████████████████████████████████████████████████████████████| 10000/10000 [3:54:28<00:00,  1.41s/it]

stuning even nongamer sound track beautiful paints senery mind well would recomend even people hate vid game music played game chrono cross games ever played best music backs away crude keyboarding takes fresher step grate guitars soulful orchestras would impress anyone cares listen
best soundtrack ever anything im reading lot reviews saying best game soundtrack figured id write review disagree bit opinino yasunori mitsudas ultimate masterpiece music timeless im listening years beauty simply refuses fadethe price tag pretty staggering must say going buy cd much money one feel would worth every penny
amazing soundtrack favorite music time hands intense sadness prisoners fate means youve played game hope distant promise girl stole star important inspiration personally throughout teen years higher energy tracks like chrono cross times scar time dreamwatch chronomantique indefinably remeniscent chrono trigger absolutely superb wellthis soundtrack amazing music probably best composers work 

In [68]:
# This code gives everything other than alphabets(. , "" \ - etc)
"""
for sentence in tqdm(df['review'].values):
    sentence = re.sub('[a-zA-Z]'," ",sentence) # consider only alphabets, rest converted to space " "
    sentence = " ".join(low.lower() for low in sentence.split() if low.lower() not in stopwords.words('english'))
    preprocessed_reviews.append(sentence.strip())
"""

'\nfor sentence in tqdm(df[\'review\'].values):\n    sentence = re.sub(\'[a-zA-Z]\'," ",sentence) # consider only alphabets, rest converted to space " "\n    sentence = " ".join(low.lower() for low in sentence.split() if low.lower() not in stopwords.words(\'english\'))\n    preprocessed_reviews.append(sentence.strip())\n'

In [67]:
preprocessed_reviews

['stuning even nongamer sound track beautiful paints senery mind well would recomend even people hate vid game music played game chrono cross games ever played best music backs away crude keyboarding takes fresher step grate guitars soulful orchestras would impress anyone cares listen',
 'best soundtrack ever anything im reading lot reviews saying best game soundtrack figured id write review disagree bit opinino yasunori mitsudas ultimate masterpiece music timeless im listening years beauty simply refuses fadethe price tag pretty staggering must say going buy cd much money one feel would worth every penny',
 'amazing soundtrack favorite music time hands intense sadness prisoners fate means youve played game hope distant promise girl stole star important inspiration personally throughout teen years higher energy tracks like chrono cross times scar time dreamwatch chronomantique indefinably remeniscent chrono trigger absolutely superb wellthis soundtrack amazing music probably best compo

## Feature Extraction

### TF- IDF: Term Frequency- Inverse Documents Frequency

In [75]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer()
x = tfidf.fit_transform(preprocessed_reviews).toarray()
pd.DataFrame(x).shape

(10000, 38702)

In [79]:
pd.DataFrame(x).head()

0      1      2      3      4      5      6      7      8      9      ...  \
0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  ...   
1    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  ...   
2    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  ...   
3    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  ...   
4    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  ...   

   38692  38693  38694  38695  38696  38697  38698  38699  38700  38701  
0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  
1    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  
2    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  
3    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  
4    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  

[5 rows x 38702 columns]

In [76]:
df['label'] = df['label'].astype('category')
df['label'] = df['label'].cat.codes

In [78]:
df['label'].value_counts()

0    5097
1    4903
Name: label, dtype: int64

In [80]:
# split the data  into train and test

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x, df['label'], test_size = 0.25, random_state = 1)

## Random Forest Classifier

In [81]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()
rf.fit(x_train,y_train)

RandomForestClassifier()

In [83]:
y_pred_train = rf.predict(x_train)
y_pred_test = rf.predict(x_test)

In [84]:
print("Training Accuracy:",accuracy_score(y_train,y_pred_train))
print("**************"*6)
print("Test Accuracy:",accuracy_score(y_test,y_pred_test))

Training Accuracy: 1.0
************************************************************************************
Test Accuracy: 0.8372


### Cross Validation

In [85]:
from sklearn.model_selection import cross_val_score
training_accuracy = cross_val_score(rf,x_train,y_train)
training_accuracy.mean()

0.8263999999999999

## Naive Bayes Theorem

## Guass NB

In [86]:
from sklearn.naive_bayes import GaussianNB

In [87]:
gnb = GaussianNB()
gnb.fit(x_train,y_train)

GaussianNB()

In [89]:
y_pred_gnb_train = gnb.predict(x_train)
y_pred_gnb_test = gnb.predict(x_test)

In [90]:
y_pred_gnb_test

array([0, 1, 0, ..., 0, 1, 1], dtype=int8)

In [91]:
print(confusion_matrix(y_train,y_pred_gnb_train))
print()
print(confusion_matrix(y_test,y_pred_gnb_test))

[[3816   24]
 [  36 3624]]

[[881 376]
 [461 782]]


In [92]:
print(classification_report(y_train,y_pred_gnb_train))
print()
print(classification_report(y_test,y_pred_gnb_test))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99      3840
           1       0.99      0.99      0.99      3660

    accuracy                           0.99      7500
   macro avg       0.99      0.99      0.99      7500
weighted avg       0.99      0.99      0.99      7500


              precision    recall  f1-score   support

           0       0.66      0.70      0.68      1257
           1       0.68      0.63      0.65      1243

    accuracy                           0.67      2500
   macro avg       0.67      0.66      0.66      2500
weighted avg       0.67      0.67      0.66      2500



In [93]:
print(accuracy_score(y_train,y_pred_gnb_train))
print()
print(accuracy_score(y_test,y_pred_gnb_test))

0.992

0.6652


In [103]:
training_accuracy = cross_val_score(gnb,x_train,y_train)
training_accuracy.mean()

0.6644

In [104]:
test_accuracy = cross_val_score(gnb,x_test,y_test)
test_accuracy.mean()

0.6332000000000001

### Bernoulli NB

In [94]:
from sklearn.naive_bayes import BernoulliNB

In [95]:
bnb = BernoulliNB()
bnb.fit(x_train,y_train)

BernoulliNB()

In [96]:
y_pred_bnb_xtrain = bnb.predict(x_train)
y_pred_bnb_xtest = bnb.predict(x_test)

In [98]:
print("Training ACcuracy:",accuracy_score(y_train,y_pred_bnb_xtrain))
print("***************"*6)
print("Test Accuracy:",accuracy_score(y_test,y_pred_bnb_xtest))

Training ACcuracy: 0.9564
******************************************************************************************
Test Accuracy: 0.8408


In [99]:
print(confusion_matrix(y_train,y_pred_bnb_xtrain))
print("***************"*6)
print(confusion_matrix(y_test,y_pred_bnb_xtest))

[[3708  132]
 [ 195 3465]]
******************************************************************************************
[[1086  171]
 [ 227 1016]]


In [102]:
print(classification_report(y_train,y_pred_bnb_xtrain))
print("***************"*6)
print(classification_report(y_test,y_pred_bnb_xtest))

              precision    recall  f1-score   support

           0       0.95      0.97      0.96      3840
           1       0.96      0.95      0.95      3660

    accuracy                           0.96      7500
   macro avg       0.96      0.96      0.96      7500
weighted avg       0.96      0.96      0.96      7500

******************************************************************************************
              precision    recall  f1-score   support

           0       0.83      0.86      0.85      1257
           1       0.86      0.82      0.84      1243

    accuracy                           0.84      2500
   macro avg       0.84      0.84      0.84      2500
weighted avg       0.84      0.84      0.84      2500



In [105]:
training_accuracy = cross_val_score(bnb,x_train,y_train)
training_accuracy.mean()

0.8345333333333332